spring:
  application:
    name: monitoring
  #  h2:
#    console:
#      enabled: true
#      path: /h2
  datasource:
#    url: jdbc:h2:mem:test
#    url: jdbc:mariadb://52.78.141.216:3306/dream?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: dev
#    password: dreamtherock
    url: jdbc:mariadb://j9a301a.p.ssafy.io:3306/s09p22a301?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: dreamtherock
#    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S09P22A301?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: S09P22A301
#    password: QmK0nwCJzS
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  level:
    com.example : DEBUG
kakao:
  client-id: 58eed44d11c6af52c6a68c04e0535346
  client-secret: bBPBGpVCVBztPXD2OW5HeBNtTUUNU5YY
  redirect-uri: http://localhost:3000/oauth/kakao
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me
  scope:
    - profile_nickname
    - profile_image
    - account_email

naver:
  client-id: jzQ_Z_TqlmAVqPcgNCwr
  client-secret: eseJBAMxn2
  redirect-uri: http://localhost:3000/oauth/naver
  token-uri: https://nid.naver.com/oauth2.0/token
  user-info-uri: https://openapi.naver.com/v1/nid/me
  scope: name, email, profile_image

google:
  client-id: 160473970613-kedt5h9uf0i2cepc82lhkpvmih1dgc3u.apps.googleusercontent.com
  client-secret: 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
  redirect-uri: http://localhost:3000/oauth/google
  token-uri: https://oauth2.googleapis.com/token
  user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
  scope: profile, email

jwt:
  refreshTokenExpirationMs: 604800000  # 7일로 설정